#!/bin/bash

echo "🔧 VPS Backend Configuration Script"
echo "=================================="
echo ""
echo "This script helps configure the VPS backend to connect to the VPS database."
echo ""
echo "📋 Required Configuration:"
echo "  VPS Backend: 64.227.99.111:8000"
echo "  VPS Database: 64.227.99.111:5432"
echo "  Database: brick_orchestration"
echo "  Username: user"
echo "  Password: password"
echo ""
echo "🔧 Environment Variable Required:"
echo "  DATABASE_URL=postgresql://user:password@64.227.99.111:5432/brick_orchestration"
echo ""
echo "📝 Steps to Configure VPS Backend:"
echo "1. SSH into your VPS server:"
echo "   ssh root@64.227.99.111"
echo ""
echo "2. Navigate to your backend directory on the VPS"
echo ""
echo "3. Update the environment configuration with:"
echo "   DATABASE_URL=postgresql://user:password@64.227.99.111:5432/brick_orchestration"
echo ""
echo "4. Restart the VPS backend service"
echo ""
echo "5. Test the connection:"
echo "   curl http://64.227.99.111:8000/api/v1/database/health"
echo ""
echo "✅ Configuration file created: vps-backend-config.env"
echo "   Use this file to configure your VPS backend environment variables."
